### ISSUE TITLE
Arduino port

### ISSUE THREAD

**Issue by gmag11** [gizmocuz/CayenneLPP-Decoder#1]
I was looking for a CayenneLPP decoder to use this format in a low power sensor system, not connected to TTN.

I found your code and it seems perfect to be ported to Arduino. Would you mind that I use a fork to build a library for this platform?

**Comment by gizmocuz** [comment]
sure no problem ! i use it their as well (started with the Arduino)

**Comment by gmag11** [comment]
It is done. I've inherited same license you use here. https://github.com/gmag11/CayenneLPPdec. It is now available on Arduino repository.

**Comment by gizmocuz** [comment]
@gmag11 , thanks ! But maybe write my name correct on the landing page ;)
